""" This file is automatically generated from "mitsuba.conf" using the script
    "resources/configure.py". Please do not attempt to change it manually,
    as any changes will be overwritten."""

PYTHON_EXECUTABLE = r"C:\Users\arpita1\Anaconda3\envs\py38\python.exe"
MTS_DEFAULT_VARIANT = 'scalar_rgb'
MTS_VARIANTS = ['scalar_rgb']
