""" This file is automatically generated from "mitsuba.conf" using the script
    "resources/configure.py". Please do not attempt to change it manually,
    as any changes will be overwritten."""

PYTHON_EXECUTABLE = r"C:\Users\arpit\anaconda3\python.exe"
MTS_DEFAULT_VARIANT = 'packet_rgb'
MTS_VARIANTS = ['scalar_rgb', 'packet_rgb']
